# Generated by Django 6.0.1 on 2026-01-29 12:19

from django.db import migrations


def populate_my_table(apps, schema_editor):
    Role = apps.get_model('api', 'role')
    my_data = [{"name": "guest"},
               {"name": "basic"},
               {"name": "manager"},
               {"name": "admin"}]
    for role in my_data:
        Role.objects.create(**role)

    User = apps.get_model('api', 'User')
    my_data = [{"username": "joe", "password": "$2b$12$QfU0BwNI.dJWJ/hEofl/SubOdQYVJ9SLr6qxbZQWiAuNe4yOZiXnS",
               "role_id": 2}]
    for user in my_data:
        User.objects.create(**user)



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_user'),
    ]

    operations = [
      migrations.RunPython(populate_my_table, migrations.RunPython.noop),
    ]


