# Generated by Django 6.0.1 on 2026-01-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_migration_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Api_User'},
        ),
    ]
